name: Circuit Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  circuit-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install circom
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific platform and architecture
          repo: iden3/circom
          tag: v2.1.9
          platform: linux
          arch: amd64

      - name: Checkout circuits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run circuit unit tests
        working-directory: zkp/js
        run: |
          npm install
          npm t
