name: Circuit Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  circuit-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout circuits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run golang e2e tests
        working-directory: zkp/js
        run: |
          npm install
          npm t
