name: e2e

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  circuit-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Checkout circom repo
        uses: actions/checkout@v4
        with:
          repository: 'iden3/circom'
          ref: 'v2.1.9'

      - name: Build circom
        run: |
          cd circom
          RUSTFLAGS="$RUSTFLAGS -A dead_code" cargo build --release
          RUSTFLAGS="$RUSTFLAGS -A dead_code" cargo install --path .

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install snarkjs
        run: |
          npm install -g snarkjs

      - name: Checkout circuits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup temp dir for the artifacts
        run: |
          mkdir -p ${{ runner.temp }}/zeto-artifacts

      - name: Build circuits
        env:
          PROVING_KEYS_ROOT: ${{ runner.temp }}/zeto-artifacts
          PTAU_DOWNLOAD_PATH: ${{ runner.temp }}/zeto-artifacts
          CIRCUITS_ROOT: ${{ runner.temp }}/zeto-artifacts
        run: |
          cd zkp/circuits
          npm install
          npm run gen
