name: Golang SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  golang-test:
    env:
      TEST_ARGS: -v
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: zeto
          fetch-depth: 0

      - name: Checkout kaleido's fork of go-iden3-crypto
        uses: actions/checkout@v3
        with:
          path: go-iden3-crypto
          repository: kaleido-io/go-iden3-crypto
          ref: multi-states
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build and Test
        working-directory: zeto/go-sdk
        run: make

      - uses: codecov/codecov-action@v4
        with:
          codecov_yml_path: ./zeto/codecov.yml
          token: ${{ secrets.CODECOV_TOKEN }}
